name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_julia_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: julia --project=. -e "using Pkg; Pkg.instantiate()"
      - run: julia --project=. -e "using Pkg; Pkg.test()"
      - run: julia --project=. LibPQ/example.jl
